import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { CourseService } from '../../services/course.service';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { IonicModule, ToastController } from '@ionic/angular';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { Course } from '../../services/course.model';

@Component({
  selector: 'app-upload',
  templateUrl: './upload.page.html',
  styleUrls: ['./upload.page.scss'],
  standalone: true,
  imports: [CommonModule, FormsModule, ReactiveFormsModule, IonicModule]
})
export class UploadPage implements OnInit {
  uploadForm: FormGroup;
  currentTeacherId: number | undefined;
  currentTeacherName: string | undefined;

  constructor(
    private fb: FormBuilder,
    private courseService: CourseService,
    private router: Router,
    private authService: AuthService,
    private toastController: ToastController
  ) {
    this.uploadForm = this.fb.group({
      title: ['', Validators.required],
      description: ['', Validators.required],
      price: ['', [Validators.required, Validators.min(0)]],
      category: ['', Validators.required],
      cover: ['assets/icon/favicon.png'] // Default cover for now
    });
  }

  ngOnInit() {
    const currentUser = this.authService.currentUserValue;
    if (currentUser && currentUser.role === 'teacher') {
      this.currentTeacherId = currentUser.id;
      this.currentTeacherName = `${currentUser.firstName} ${currentUser.lastName}`;
    } else {
      // Handle case where non-teacher user tries to access (though RoleGuard should prevent this)
      this.presentToast('You are not authorized to upload courses.', 'danger');
      this.router.navigate(['/home']);
    }
  }

  async uploadCourse() {
    if (this.uploadForm.valid && this.currentTeacherId && this.currentTeacherName) {
      const newCourse: Course = {
        id: 0, // ID will be generated by the service
        teacherId: this.currentTeacherId,
        author: this.currentTeacherName,
        rating: 0, // Initial rating
        enrolled: false, // Initial enrollment status
        modules: [], // No modules initially
        createdAt: new Date(),
        updatedAt: new Date(),
        ...this.uploadForm.value
      };

      this.courseService.createCourse(newCourse).subscribe(
        async createdCourse => {
          await this.presentToast('Course uploaded successfully!', 'success');
          this.uploadForm.reset();
          this.router.navigate(['/teacher-dashboard']);
        },
        async error => {
          console.error('Error uploading course:', error);
          await this.presentToast('Failed to upload course. Please try again.', 'danger');
        }
      );
    } else {
      await this.presentToast('Please fill all required fields.', 'danger');
    }
  }

  async presentToast(message: string, color: string = 'primary') {
    const toast = await this.toastController.create({
      message: message,
      duration: 2000,
      color: color
    });
    toast.present();
  }
}